### ISSUE TITLE
Pre-trained Model

### ISSUE THREAD

**Issue by FrancescaCi** [dbsousa01/PAD-LSTM#2]
Hi,
We are interested at your project, we would like to test your pretrained models on our dataset, Could you share the files, please?

Thank you so much.
Best,
Francesca

**Comment by dbsousa01** [comment]
Hi Francesca!

Thank you for your interest! Unfortunately, I no longer have access to the model itself, only its training code. I've did this work during my Master Thesis, almost 4 years ago, so when I left, all my models were left on the training computer which belonged to the University. All I have its the report and the training code which you can use freely!

Hope it helps,
Best,
Daniel
